# Generated by Django 5.0.4 on 2024-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_end_date_quiz_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
